package com.crud.producto.productos.modelo;


public enum Categoria {
    ALIMENTOS_Y_BEBIDAS,
    PRODUCTOS_DE_LIMPIEZA,
    ELECTRODOMESTICOS_Y_ELECTRONICA,
    PRODUCTOS_DE_HIGIENE_PERSONAL,
    TEXTILES_Y_ROPA,
    MOBILIARIO_Y_DECORACION,
    MATERIALES_DE_CONSTRUCCION_Y_FERRETERIA,
    PAPELERIA_Y_OFICINA,
    PRODUCTOS_FARMACEUTICOS_Y_MEDICOS,
    AUTOMOTRIZ,
    PRODUCTOS_DE_JARDINERIA,
    JUGUETERIA_Y_ENTRETENIMIENTO,
    MASCOTAS,
    PRODUCTOS_QUIMICOS
}